### ISSUE TITLE
lose "ParseKeys.h"

### ISSUE THREAD

**Issue by ThreeStar** [itsniper/FTASync#16]
Hi,

Just I clone the code,but when i open the project,i found it lost the file "ParseKeys.h".

What's this file? set the parse's app id and client id?

**Comment by alexsaidani** [comment]
My bad ignore how patronising the answer below is, I thought it was a stupid question then I realised what you meant. Yeah that file is for the Parse App and Client IDs.

You'll have to create the file yourself, make sure you have the group you wish the file to be in. Click File > New > File, then select C and C++, then choose a header file (.h). Save the file into the project and then open it up in Xcode from within your project. Then all you've got to do is add the following lines to your code:

#define kParseAppId @"Parse-App-ID"
#define kParseClientKey @"Parse-Client-ID"

Obviously adding your own Parse App and Client IDs. Best of luck!
